-- Clean up existing data
TRUNCATE categories, products, users RESTART IDENTITY CASCADE;

-- Insert categories
INSERT INTO categories (id, title, slug, img_src, alt, description) VALUES
  (1, 'Polos', 'polos', '/images/polos.jpg', 'Hombre luciendo polo azul', 'Polos exclusivos con diseños que todo desarrollador querrá lucir. Ideales para llevar el código a donde vayas.'),
  (2, 'Tazas', 'tazas', '/images/tazas.jpg', 'Tazas con diseño de código', 'Tazas que combinan perfectamente con tu café matutino y tu pasión por la programación. ¡Empieza el día con estilo!'),
  (3, 'Stickers', 'stickers', '/images/stickers.jpg', 'Stickers de desarrollo web', 'Personaliza tu espacio de trabajo con nuestros stickers únicos y muestra tu amor por el desarrollo web.');

-- Insert products
INSERT INTO products (id, title, img_src, price, description, category_id, is_on_sale, features) VALUES
  -- Polos
  (1, 'Polo React', '/images/polos/polo-react.png', 20.00, 'Viste tu pasión por React con estilo y comodidad en cada línea de código.', 1, false, 
    ARRAY['Estampado resistente que mantiene sus colores vibrantes lavado tras lavado.',
          'Hecho de algodón suave que asegura comodidad y frescura.',
          'Costuras reforzadas para una mayor durabilidad.',
          'Corte moderno que se adapta perfectamente al cuerpo.']),
  (2, 'Polo JavaScript', '/images/polos/polo-js.png', 20.00, 'Deja que tu amor por JavaScript hable a través de cada hilo de este polo.', 1, false,
    ARRAY['Logo de JavaScript bordado con precisión y detalle.',
          'Tela premium de algodón peinado.',
          'Disponible en varios colores.',
          'Acabado profesional con doble costura.']),
  (3, 'Polo Node.js', '/images/polos/polo-node.png', 20.00, 'Conéctate al estilo con este polo de Node.js, tan robusto como tu código.', 1, false,
    ARRAY['Diseño minimalista con el logo de Node.js.',
          'Material transpirable ideal para largas sesiones de código.',
          'Tejido resistente a múltiples lavados.',
          'Etiqueta sin costuras para mayor comodidad.']),
  (4, 'Polo TypeScript', '/images/polos/polo-ts.png', 20.00, 'Tipa tu estilo con precisión: lleva tu pasión por TypeScript en cada hilo.', 1, false,
    ARRAY['Logo de TypeScript estampado en alta calidad.',
          'Tejido antimanchas y duradero.',
          'Cuello reforzado que mantiene su forma.',
          '100% algodón hipoalergénico.']),
  (5, 'Polo Backend Developer', '/images/polos/polo-backend.png', 25.00, 'Domina el servidor con estilo: viste con orgullo tu título de Backend Developer.', 1, false,
    ARRAY['Diseño exclusivo para desarrolladores backend.',
          'Material premium que mantiene su forma.',
          'Costuras reforzadas en puntos de tensión.',
          'Estampado de alta durabilidad.']),
  (6, 'Polo Frontend Developer', '/images/polos/polo-frontend.png', 25.00, 'Construye experiencias con estilo: luce con orgullo tu polo de Frontend Developer.', 1, false,
    ARRAY['Diseño inspirado en elementos de UI/UX.',
          'Tela suave y ligera perfecta para el día a día.',
          'Estampado flexible que no se agrieta.',
          'Acabado profesional en cada detalle.']),
  (7, 'Polo Full-Stack Developer', '/images/polos/polo-fullstack.png', 25.00, 'Domina ambos mundos con estilo: lleva tu título de FullStack Developer en cada línea de tu look.', 1, false,
    ARRAY['Diseño que representa ambos mundos del desarrollo.',
          'Material premium de larga duración.',
          'Proceso de estampado ecológico.',
          'Corte moderno y cómodo.']),
  (8, 'Polo It''s A Feature', '/images/polos/polo-feature.png', 15.00, 'Cuando el bug se convierte en arte: lleva con orgullo tu polo ''It''s a feature''.', 1, true,
    ARRAY['Estampado humorístico de alta calidad.',
          'Algodón orgánico certificado.',
          'Diseño exclusivo de la comunidad dev.',
          'Disponible en múltiples colores.']),
  (9, 'Polo It Works On My Machine', '/images/polos/polo-works.png', 15.00, 'El clásico del desarrollador: presume tu confianza con ''It works on my machine''.', 1, true,
    ARRAY['Frase icónica del mundo del desarrollo.',
          'Material durable y cómodo.',
          'Estampado que no se desvanece.',
          'Ideal para regalo entre desarrolladores.']),
          
  -- Stickers
  (10, 'Sticker JavaScript', '/images/stickers/sticker-js.png', 2.99, 'Muestra tu amor por JavaScript con este elegante sticker clásico.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (11, 'Sticker React', '/images/stickers/sticker-react.png', 2.49, 'Decora tus dispositivos con el icónico átomo giratorio de React.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (12, 'Sticker Git', '/images/stickers/sticker-git.png', 3.99, 'Visualiza el poder del control de versiones con este sticker de Git.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (13, 'Sticker Docker', '/images/stickers/sticker-docker.png', 2.99, 'La adorable ballena de Docker llevando contenedores en un sticker único.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (14, 'Sticker Linux', '/images/stickers/sticker-linux.png', 2.49, 'El querido pingüino Tux, mascota oficial de Linux, en formato sticker.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (15, 'Sticker VS Code', '/images/stickers/sticker-vscode.png', 2.49, 'El elegante logo del editor favorito de los desarrolladores.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (16, 'Sticker GitHub', '/images/stickers/sticker-github.png', 2.99, 'El alojamiento de repositorios más popular en un sticker de alta calidad.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
  (17, 'Sticker HTML', '/images/stickers/sticker-html.png', 2.99, 'El escudo naranja de HTML5, el lenguaje que estructura la web.', 3, false,
    ARRAY['Vinilo de alta calidad resistente al agua',
          'Adhesivo duradero que no deja residuos',
          'Colores vibrantes que no se desvanecen',
          'Tamaño perfecto para laptops y dispositivos']),
          
  -- Mugs
  (18, 'Taza JavaScript', '/images/tazas/taza-js.png', 14.99, 'Disfruta tu café mientras programas con el logo de JavaScript.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']),
  (19, 'Taza React', '/images/tazas/taza-react.png', 13.99, 'Una taza que hace render de tu bebida favorita con estilo React.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']),
  (20, 'Taza Git', '/images/tazas/taza-git.png', 12.99, 'Commit a tu rutina diaria de café con esta taza de Git.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']),
  (21, 'Taza SQL', '/images/tazas/taza-sql.png', 15.99, 'Tu amor por los lenguajes estructurados en una taza de SQL.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']),
  (22, 'Taza Linux', '/images/tazas/taza-linux.png', 13.99, 'Toma tu café con la libertad que solo Linux puede ofrecer.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']),
  (23, 'Taza GitHub', '/images/tazas/taza-github.png', 14.99, 'Colabora con tu café en esta taza con el logo de GitHub.', 2, false,
    ARRAY['Cerámica de alta calidad',
          'Apta para microondas y lavavajillas',
          'Capacidad de 325ml',
          'Diseño que no pierde color con el uso']);

-- Reset sequence to the last used id
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM categories));
